---
# tasks file for docker.ubuntu

# These are the version of Ubuntu for which this role has been tested.
- name: Fail if not a new release of Ubuntu
  fail: msg="{{ ansible_distribution_version }} is not an acceptable version of Ubuntu for this role"
  when: "ansible_distribution_version not in ['12.04', '13.04', '13.10', '14.04', '16.04']"

- name: check that docker_version is set
  fail: msg="Required variable \"docker_version\" is not defined."
  when: docker_version is not defined

# https://docs.docker.com/installation/ubuntulinux/
- name: Install backported kernel on pre-16.04 LTS
  apt:
    pkg: "{{ item.name }}"
    state: latest
    update_cache: yes
    cache_valid_time: "{{ docker_role_apt_cache_valid_time }}"
  with_items:
    - name: linux-image-generic-lts-trusty
      version: "12.04"
    - name: linux-headers-generic-lts-trusty
      version: "12.04"
    - name: linux-image-generic-lts-xenial
      version: "14.04"
  register: kernel_result
  when: ansible_distribution_version == item.version

- name: Install latest kernel extras for Ubuntu 13.04, 13.10
  apt:
    pkg: "linux-image-extra-{{ ansible_kernel }}"
    state: "{{ kernel_pkg_state }}"
    update_cache: yes
    cache_valid_time: "{{ docker_role_apt_cache_valid_time }}"
  when: ansible_distribution_version in ['13.04', '13.10']

# Fix for https://github.com/dotcloud/docker/issues/4568
- name: Install cgroup-lite for Ubuntu 13.10
  apt:
    pkg: cgroup-lite
    state: "{{ cgroup_lite_pkg_state }}"
    update_cache: yes
    cache_valid_time: "{{ docker_role_apt_cache_valid_time }}"
  register: cgroup_lite_result
  when: ansible_distribution_version == '13.10'

- name: Is reboot necessary?
  set_fact:
    reboot_needed: "{{(kernel_result or cgroup_lite_result or {'changed': False}) | changed}}"

- include: reboot-and-wait.yml

# Newer versions of Docker no longer require apparmor, but it seems like a good thing to have.
- name: Install apparmor
  apt: pkg=apparmor state=present

- name: Write /etc/default/docker config file
  template: src=etc_default_docker.j2 dest=/etc/default/docker
  register: r_etc_default_docker

- name: Install LXC Docker
  include: lxc-docker.yml
  when: docker_version == '1.5.0'

- name: Install Docker Engine
  include: docker-engine.yml
  when: docker_version != '1.5.0'

# if we changed the config, but didn't reinstall docker, then restart it
- name: Restart docker on config change
  service: name=docker state=restarted
  when: r_etc_default_docker|changed and not r_docker_package_install|changed

- name: Ensure that Docker is running
  service: name="docker" state=started

- name: Wait until docker daemon is available
  command: docker info
  register: r_docker_info
  # need a special case here, or this always fails in check mode.
  until: r_docker_info|skipped or r_docker_info.rc == 0
  retries: "{{ docker_daemon_startup_timeout_sec }}"
  delay: 1

- name: reread docker facts
  setup: filter=ansible_docker0
  when: r_etc_default_docker|changed or r_docker_package_install|changed

- name: Check if /etc/default/ufw exists
  stat: path=/etc/default/ufw
  register: ufw_default_exists

- name: Change ufw default forward policy from drop to accept
  lineinfile:
    dest: /etc/default/ufw
    regexp: "^DEFAULT_FORWARD_POLICY="
    line: "DEFAULT_FORWARD_POLICY=\"ACCEPT\""
  when: ufw_default_exists.stat.exists
